### ISSUE TITLE
Support docker daemon running on host (mesos slave) which listens on unix socket only.

### ISSUE THREAD

**Issue by FlorianGrundig** [mesos/logstash#12]
Currently we assume that the docker daemon listens on a tcp port 2376.

**Comment by jhftrifork** [comment]
@mwl can we close this? I don't think we have this assumption any more. I think it was from a time when we were following `docker logs`?

**Comment by FlorianGrundig** [comment]
Hi,
this has nothing to do with `docker logs` it's just, that in the default mesos cluster environment the docker daemon listens on the unix socket not on the tcp port... So to avoid have the admin to install the docker daemon on the tcp port for all the mesos nodes, we should support having the docker daemon running on tcp or socket...

**Comment by FlorianGrundig** [comment]
Ah - sorry accidentally I reopened it... I will close it but reopen if you agree...
