### ISSUE TITLE
Executor should match configuration and running frameworks rather by regular expression than exact image names

### ISSUE THREAD

**Issue by FlorianGrundig** [mesos/logstash#13]
In the UI the docker configuration header is used to match the framework to observe:

E.g. if the docker configuration header is set to "busybox:latest" it will monitor only running container with an exact match by image name. 

It would be much better if you could use regex as image names - something like "busybox:*" or ".*chronos.*".

**Comment by drewrobb** [comment]
I've also noticed it is a bit confusing for the "docker configuration header" to also be referred to as frameworkName at some places, when it only has to do with a docker image name.

**Comment by epeld** [comment]
We might want to stop using the configuration file name to match against image names. It doesn't feel right to put a regex in a file name.

It would be easy enough to let the web UI's /config-page support regexes though.

**Comment by jhftrifork** [comment]
@mwl I think we can close this too?
