### ISSUE TITLE
The web UI the logstash configuration-file that each executor is using

### ISSUE THREAD

**Issue by epeld** [mesos/logstash#27]
We perform a lot of "configuration magic" based on which docker containers we encounter on each mesos slave.

It should be possible to see exactly how the logstash process is configured within each executor in the cluster.

Implementation note:
The executors already produce their own logstash configuration files. Implementing this is just a matter of attaching the whole configuration string when sending a status update back to the scheduler

**Comment by frankscholten** [comment]
Out of date
