### ISSUE TITLE
Implement option for enforcing execution on all slaves

### ISSUE THREAD

**Issue by epeld** [mesos/logstash#29]
Currently, the scheduler launches a new logstash instance on every slave that it is offered.

If another framework already utilizes a slave heavily, that slave will not be offered to us and will therefore not run logstash.

We should consider providing a mechanism that *enforces* that the scheduler be offered all slaves in the cluster.

**Comment by hekaldama** [comment]
FWIW, I would love to have a framework that would give me the ability to ensure a given task (E.g. daemon) was running across *all* mesos-agents. Seems like this logstash framework does that for just logstash-forwarder, but I wonder if we could extract out the "framework that forces running a task on all mesos-agents" for general use, and this project uses that for launching logstash-forwarders.

Does that make sense?

**Comment by frankscholten** [comment]
You can already do this with Marathon and constraints https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md
