### ISSUE TITLE
Specify elasticsearch configuration

### ISSUE THREAD

**Issue by ktf** [mesos/logstash#31]
I'd like to specify my own elasticsearch endpoint. How do I do that?

**Comment by frankscholten** [comment]
See the example configuration in the 'Config' section in https://github.com/mesos/logstash/blob/master/README.md

**Comment by ktf** [comment]
Thanks. The problem seems to be due to the fact the logstash you use is different from the one I had, and the configuration takes `host => string` rather than `hosts => list`.
