### ISSUE TITLE
Replace system properties with command line options

### ISSUE THREAD

**Issue by frankscholten** [mesos/logstash#35]
See https://github.com/mesos/elasticsearch/tree/master/commons/src/main/java/org/apache/mesos/elasticsearch/common/cli

**Comment by jhftrifork** [comment]
@mwl I think we can close this -- you replaced it with the Spring Boot config thingamajig which lets us use command-line options

**Comment by mwl** [comment]
It means, replace `java  -Dfoo=far -jar …` with `java -jar … --foo=bar`. Anyway. It's included in my Spring refactoring.
