### ISSUE TITLE
Executor should use a more reliable mechanism to observe files

### ISSUE THREAD

**Issue by FlorianGrundig** [mesos/logstash#4]
Currently if we want to observe a log file we stream the content into a separate file in the executor container itself. The file is therefor a kind of mirrored and that mirrored file inside the executor container is observed by logstash. To limit the file size of these mirrored/streamed files we cut of the content after (currently fixed) 5 MegaBytes. That means after reaching that limit we delete the mirrored file and start from position 0. With that approach we can not assure that the content before deleting the file and start from position 0 was processed by logstash. Some lines in the log file might not observed and therefor not monitored. 
Replace the current file mirroring and cutting of with something more reliable...

**Comment by FlorianGrundig** [comment]
lguminski [9:35 AM] 
you could also investigate how monitoring tools hook into containers - read this
https://blog.ruxit.com/how-to-monitor-docker-containers/
I think they make a LD_PRELOAD trick similar to `stdbuf` http://www.pixelbeat.org/programming/stdio_buffering/

**Comment by jhftrifork** [comment]
Not monitoring files any more
