### ISSUE TITLE
Run executors without Docker

### ISSUE THREAD

**Issue by frankscholten** [mesos/logstash#40]

**Comment by mwl** [comment]
@philwinder Please take a look at this

**Comment by philwinder** [comment]
This looks reasonable. Logstash is distributed as a zip, the executor is distributed as a jar. We can have a fileserver on the scheduler that provides the URI's so that Mesos can download them. Mesos is also able to extract from zips, so we can do that too. Then we just need the configuration options.

**Comment by frankscholten** [comment]
- [ ] Add SimpleFileServer
- [ ] Add web server endpoint for executor
- [ ] Add web server endpoint for logstash binary
- [ ] Update code in TaskInfoFactory
- [ ] Update Gradle build so logstash binary is packaged inside scheduler jar
- [ ] Testing

**Comment by mwl** [comment]
> Then we just need the configuration options
The executor should be picking them up automagically over protobuf. So what's the issue?

**Comment by philwinder** [comment]
@frankscholten you don't need a webserver. Spring aready has one. I had already done this. Also you need a Gradle task to download the logstash zip. See my code.

**Comment by frankscholten** [comment]
@philwinder where is your code?

**Comment by philwinder** [comment]
@mwl I meant CLI options to enable jar mode. (Or whatever configuration type you use)

**Comment by frankscholten** [comment]
Got it https://github.com/philwinder/logstash/tree/feature/jarMode

**Comment by mwl** [comment]
Ah! Just add field/getter/setter to `org.apache.mesos.logstash.config.FrameworkConfig` and Spring will do it's magic.

**Comment by frankscholten** [comment]
It turns out unzip was not installed on the [minimesos Docker images](https://github.com/ContainerSolutions/minimesos-docker) so the logstash zip [was not unzipped](https://github.com/ContainerSolutions/minimesos/issues/200).

**Comment by mwl** [comment]
A few open tasks left, which are not relevant anymore.
