### ISSUE TITLE
gradlew build fails

### ISSUE THREAD

**Issue by suppandi** [mesos/logstash#46]
after nov 13 update, build fails and leaves a message

Could not find method idea() for arguments [build_2fao9yuf8kuoutww4z5toe0rq$_run_closure4@5ed0b4e3] on project ':logstash-commons'.

**Comment by suppandi** [comment]
adding 
allprojects {
    apply plugin: 'idea'
}

to build.gradle fixed it

**Comment by frankscholten** [comment]
Fixed in https://github.com/mesos/logstash/commit/3d5595ab69952e0a5485862de1d1d4a11d262427
