### ISSUE TITLE
Connect logstash to ElasticSearch

### ISSUE THREAD

**Issue by mwl** [mesos/logstash#50]
Tasks:

- [x] Deploy a singlenode ES to minimesos (@mwl)
- [ ] Deploy Logstash to minimesos and point it to ElasticSearch (@jhftrifork)
- [ ] Run `logger -n localhost:???? "RANDOM GENERATED TOKEN"` on a random node
- [ ] assert ES has "RANDOM GENERATED TOKEN".

**Comment by frankscholten** [comment]
This issue is continued here https://github.com/ContainerSolutions/mesos-elk-demo
