### ISSUE TITLE
CollectD support

### ISSUE THREAD

**Issue by mwl** [mesos/logstash#52]
Logstash has a [CollectD codec](https://www.elastic.co/guide/en/logstash/1.5/plugins-codecs-collectd.html) plugin which can be used for receiving CollectD data

# Tasks
- [x] Enable CollectD endpoint

**Comment by frankscholten** [comment]
The collectd container + config is already added. Anything else that has to be done for this issue?

**Comment by mwl** [comment]
This is already done. Forgot to close.
