### ISSUE TITLE
Tag log events with ID of Mesos slave

### ISSUE THREAD

**Issue by jhftrifork** [mesos/logstash#53]
Each Logstash instance should tag all the log events that go through it with the id of that Logstash instance (e.g. the id of the Mesos slave it is running on).

Motivations:

* debuggability and auditing of where logs came from
* disambiguation of some kinds of log, e.g. if a Mesos slave complains “out of memory”, we’ll get an "out of memory” log line, but won’t necessarily know which slave is complaining

**Comment by jhftrifork** [comment]
https://github.com/mesos/logstash/pull/66

**Comment by mwl** [comment]
Fixed by #66
