### ISSUE TITLE
Docker logs logging

### ISSUE THREAD

**Issue by FlorianGrundig** [mesos/logstash#7]
The framework should observe the docker logs output.

**Comment by epeld** [comment]
By this, we mean that the logstash framework should be able to capture (and process) the output of `docker log` for any container running on the slaves.

**Comment by jhftrifork** [comment]
@mwl is this still a desired feature? IMO Logstash should be "listen-only" rather than going out of its way to capture anything

**Comment by mwl** [comment]
Agreed.
